### ISSUE TITLE
How to compile this code?

### ISSUE THREAD

**Issue by asiniy** [justintconroy/MdbBillValidator#2]
Can you explain briefly how can you compile & upload this code, please?

**Comment by justintconroy** [comment]
I used the Arduino IDE to compile and upload this to an Arduino Uno. This is just a library that can be called by an arduino program. You need to find your Libraries folder for your arduino environment. I might be able to upload a more detailed readme and a sample program in a couple of days...

**Comment by asiniy** [comment]
Justin, thx!

**Comment by asiniy** [comment]
It still will be great if you'll share an examples.

BTW, I'm use arduino mega 2560 now, and I want to use port 0 as serial monitor for arduino mega ide, and port 1 as mdb connector. How can I do that?

**Comment by justintconroy** [comment]
It won't be possible to use the hardware serial port on an Arduino as a serial monitor if you use this library. This library is basically a modification of the HardwareSerial library that comes with the standard Arduino stuff. So it uses the standard hardware serial port. If you want to have a serial monitor, you'll have to use SoftwareSerial.

**Comment by justintconroy** [comment]
I added a couple of sample programs to the repository. Again, I haven't had a chance to test this recently, so no guarantee that they actually work, and definitely no guarantee that they'll work on a Mega, but they should at least sort of show how to use the library.
